In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
#Exercise 1: Array Creation and Manipulation
d_array = np.arange(10)
print(d_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Exercise 2: Type conversion and Array Operations
#Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.
list_to_array = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
print(list_to_array)

[3 2 0 1 2]


In [ ]:
#Exercise 3: Working with multidimensional array
#create a 3x3 NumPy array with values ranging from 1 to 9.

multi_array = np.arange(1, 10).reshape(3, 3)
print(multi_array)

#Expected output:
#array([[1, 2, 3],
             #[4, 5, 6],
             #[7, 8, 9]])



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Exercise  4: Creating Multi-dimensional array with random numbers
#Create a 2D NumPy array of shape (4, 5) filled with random numbers. = np.random.rand(rows, columns))
array_a = np.random.rand(4, 5)
print(array_a)
#Expected Output:
#array([[0.56, 0.85, 0.01, 0.42, 0.68],
  #    [0.22, 0.37, 0.73, 0.93, 0.39],
   #    [0.44, 0.03, 0.87, 0.02, 0.83],
    #   [0.78, 0.87, 0.98, 0.80, 0.46]])


[[0.99854466 0.03935494 0.0962366  0.06087329 0.42204325]
 [0.77945429 0.10788117 0.27094457 0.64803299 0.28656652]
 [0.98079812 0.52588487 0.52180103 0.28018125 0.14272617]
 [0.87428871 0.0913729  0.48494596 0.90496585 0.88267851]]


In [ ]:
#Exercise 5: Select the second row from a given 2D numpy array
numpy_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_row = numpy_array[1]
print(second_row)

#Explained:
#numpy_array[0] -> First Row
#numpy_array[1] -> Second Row
#numpy_array[2] -> Third Row

[4 5 6]


In [ ]:
#Exercise 6: Reversing Elements
#Reverse the order of elements in a given 1D NumPy array (first element becomes the last)

array_b = np.array([1, 2, 3, 4, 5])
reversed_array = array_b[::-1]
print(reversed_array)

[5 4 3 2 1]


In [ ]:
#Exercise 7: Identity Matrix
#Create a 4x4 identity matrix using numpy
identity_matrix = np.eye(4)
print(identity_matrix)
#

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Exercise 8: Simple Aggregate Functions
#Find the sum and average of a given 1D array
array_n = np.array([2,4,6,8])
array_sum = np.sum(array_n)
array_average = np.mean(array_n)
print(array_sum)
print(array_average)

20
5.0


In [ ]:
#Exercise 9: Create Array  and change its structure
#create a numpy array with elements from 1 to 20; then reshape it into a 4x5  matrix
array_c = np.arange(1, 21).reshape(4, 5)
print(array_c)
#array_c_sum = np.sum(array_c) -> for sum
#print(array_c_sum)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
210


In [49]:
#Exercise 10: Extract all odd numbers from a given NumPy array

arr = np.arange(100)
# Extract all odd numbers from the array
odd_arr = arr[arr % 2 != 0]
print(odd_arr)



#Extra Work: Extracting all even numbers
even_arr = arr[arr % 2 == 0]
print(even_arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
